import { FormEvent, useEffect, useState } from 'react'
import { Boxes, ClipboardList, LoaderCircle, LogOut, ShieldCheck, UserRound } from 'lucide-react'
import { FulfilmentOrder, StaffUser, staffApi } from './api'

type Workspace = 'fulfilment' | 'catalogue' | 'business'
const labels: Record<Workspace, string> = { fulfilment: 'Order fulfilment', catalogue: 'Product administration', business: 'Business management' }
function message(error: unknown) { return error instanceof Error ? error.message : 'Something went wrong. Please try again.' }
function permitted(user: StaffUser, workspace: Workspace) { return workspace === 'fulfilment' ? user.roles.some(role => role === 'FulfilmentEmployee' || role === 'SystemAdministrator') : workspace === 'catalogue' ? user.roles.some(role => role === 'ProductAdministrator' || role === 'SystemAdministrator') : user.roles.some(role => role === 'BusinessManager' || role === 'SystemAdministrator') }

export function App() {
  const [user, setUser] = useState<StaffUser | null>(null), [workspace, setWorkspace] = useState<Workspace>('fulfilment')
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  useEffect(() => { if (user && !permitted(user, workspace)) setWorkspace(user.roles.includes('FulfilmentEmployee') ? 'fulfilment' : user.roles.includes('ProductAdministrator') ? 'catalogue' : 'business') }, [user, workspace])
  async function signIn(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { setUser(await staffApi.signIn(email, password)) } catch (value) { setError(message(value)) } finally { setBusy(false) } }
  if (!user) return <main className="login"><section><p className="eyebrow"><ShieldCheck/> Mzansi Market</p><h1>Staff portal</h1><p>Sign in with an administrator-issued staff account. Customer and reseller accounts cannot access this portal.</p>{error && <p className="error" role="alert">{error}</p>}<form onSubmit={signIn}><label>Email address<input type="email" value={email} onChange={event => setEmail(event.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" required/></label><button disabled={busy}>{busy && <LoaderCircle className="spin"/>}Sign in securely</button></form></section></main>
  return <div className="portal"><header><div><p className="eyebrow"><ShieldCheck/> Mzansi Market</p><strong>Staff portal</strong></div><div className="identity"><UserRound/><span>{user.displayName}</span><button onClick={async () => { await staffApi.signOut(); setUser(null) }}><LogOut/> Sign out</button></div></header><div className="layout"><nav aria-label="Staff workspace">{(['fulfilment', 'catalogue', 'business'] as Workspace[]).filter(item => permitted(user, item)).map(item => <button key={item} onClick={() => setWorkspace(item)} aria-current={workspace === item ? 'page' : undefined}>{item === 'fulfilment' ? <ClipboardList/> : <Boxes/>}{labels[item]}</button>)}</nav><main>{workspace === 'fulfilment' ? <Fulfilment /> : <PendingWorkspace title={labels[workspace]}/>}</main></div></div>
}

function Fulfilment() {
  const [orders, setOrders] = useState<FulfilmentOrder[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [busy, setBusy] = useState('')
  async function load() { setLoading(true); setError(''); try { setOrders(await staffApi.fulfilment()) } catch (value) { setError(message(value)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  async function advance(order: FulfilmentOrder) { const action = order.status === 'ReadyForFulfilment' ? 'StartPicking' : order.status === 'Picking' ? 'Pack' : ''; if (!action) return; setBusy(order.sellerOrderId); try { await staffApi.transition(order.sellerOrderId, action); await load() } catch (value) { setError(message(value)) } finally { setBusy('') } }
  return <section><p className="eyebrow"><ClipboardList/> Operations</p><h1>Fulfilment queue</h1><p>Live paid-order work queue. Every status transition is authorized and recorded by the API.</p>{error && <p className="error" role="alert">{error}</p>}{loading ? <p className="loading"><LoaderCircle className="spin"/> Loading orders…</p> : orders.length === 0 ? <div className="empty">No orders currently need fulfilment.</div> : <div className="orders">{orders.map(order => <article key={order.sellerOrderId}><div><strong>{order.orderNumber}</strong><span>{order.status}</span></div><p>{order.recipientName} · {order.city}, {order.province}</p><p>{order.items.map(item => `${item.productName} ×${item.quantity}`).join(', ')}</p>{order.status === 'ReadyForFulfilment' || order.status === 'Picking' ? <button disabled={busy === order.sellerOrderId} onClick={() => void advance(order)}>{busy === order.sellerOrderId ? 'Updating…' : order.status === 'ReadyForFulfilment' ? 'Start picking' : 'Pack order'}</button> : <small>Dispatch and delivery require carrier/tracking support in the next portal unit.</small>}</article>)}</div>}</section>
}

function PendingWorkspace({ title }: { title: string }) { return <section><p className="eyebrow"><Boxes/> Staff tools</p><h1>{title}</h1><p>This workspace is access-controlled and ready for its API integration.</p><div className="empty"><strong>Server contract in progress</strong><p>Product management, reporting, returns, and refund decisions will use live API data. No mock business data is shown here.</p></div></section> }
